CREATE TABLE IF NOT EXISTS Parent(
	Parent_ID INT(25) UNSIGNED NOT NULL AUTO_INCREMENT,
	CustomerID INT(25) UNSIGNED,
	FOREIGN KEY (CustomerID) REFERENCES Customer(ID),
	PRIMARY KEY (Parent_ID)
);

CREATE TABLE IF NOT EXISTS Child(
	Child_ID INT(25) UNSIGNED NOT NULL AUTO_INCREMENT,
	CustomerID INT(25) UNSIGNED,
	Parent_ID INT(25) UNSIGNED,
	FOREIGN KEY (CustomerID) REFERENCES Customer(ID),
	FOREIGN KEY (Parent_ID) REFERENCES Parent(Parent_ID),
	PRIMARY KEY (Child_ID)
);