INSERT INTO `customer` VALUES (0,'Unavailable','M',NULL,NULL,NULL,NULL,NULL,'This customer is used for Unavailable appointments, and no other purpose. This is to prevent the foreign key constraint from failing.',NULL,NULL);
INSERT INTO `customer` VALUES (3,'Joe Swanson','M','631-111-2222','','swansonj@hotmail.com','','1989-09-08','','T','T');
INSERT INTO `customer` VALUES (4,'Laura-Jean Bonacore','F','','','ljrunner4@yahoo.com','','1964-08-31','Mother of Bonacore children, longer notes, allergies','T','F');
INSERT INTO `customer` VALUES (5,'Ari Gold','M','631-777-8888','','golda@gmail.com','','1969-09-08','','F','T');
INSERT INTO `customer` VALUES (6,'Barbara Jones','F','631-123-4567','631-567-1111','','51 Budenos Dr, Sayville, NY, 11782','1960-12-18','','F','T');
INSERT INTO `customer` VALUES (7,'Christian Bonacore','M','631-433-2215','631-589-6415','christian.bonacore@gmail.com','2 Sampson Street, Sayville, NY 11782','1989-09-08','Developer of web site','T','T');
INSERT INTO `customer` VALUES (8,'Dylan Bonacore','M','631 555 1514','','dbon100@gmail.com','','1994-12-08','Youngest Bonacore brother, goes to Oneonta','T','F');
INSERT INTO `customer` VALUES (9,'Joseph Jones','M','631-111-4567','','jonesj@highschool.com','51 Budenos Dr, Sayville, NY, 11782','1992-11-11','Son of Barbara','T','F');
INSERT INTO `customer` VALUES (10,'Mike Jones','M','631-222-1133','','jonesm@gmail.com','','1990-10-11','Son of Barbara Jones','T','T');
INSERT INTO `customer` VALUES (11,'Mary Smith','F','631-333-2222','','smithm@hotmail.com','55 Kemi Lane, Sayville, NY, 11782','1969-03-11','Just one female customer','T','T');
INSERT INTO `customer` VALUES (12,'Vince Chase','M','631-111-4444','631-589-8899','chasev@yahoo.com','','1989-10-03','just one male customer','T','T');
INSERT INTO `customer` VALUES (13,'Connor O\'Neil','M','631-555-1439','','coneil@marist.edu','Colton Ave, Sayville, NY 11782','1994-12-03','Dylan\'s friend','T','T');
INSERT INTO `customer` VALUES (14,'Billy O\'Connor','M','631-906-4431','','boc47@aim.com','','1989-11-11','','T','T');
INSERT INTO `customer` VALUES (15,'Chris Deluca','M','631-666-5885','','dukes32@gmail.com','32 Colton Ave, Sayville, NY 11782','1989-05-15','','T','T');
INSERT INTO `customer` VALUES (16,'John Deluca','M','631-666-5887','','johnny@gotm.com','32 Colton Ave, Sayville, NY 11782','1987-06-10','','T','T');
INSERT INTO `customer` VALUES (17,'Joe Deluca','M','631-666-5889','','joe@cortland.edu','32 Colton Ave, Sayville, NY 11782','1992-05-15','','T','T');
INSERT INTO `customer` VALUES (18,'Linda Deluca','F','631-666-5891','','mrs.deluca@gmail.com','32 Colton Ave, Sayville, NY 11782','1964-05-15','','T','T');
INSERT INTO `customer` VALUES (20,'Jonathan Bonacore','M','631 589 5566','','jonbonacore@gmail.com','222 St, San Francisco, CA','1991-09-21','','T','T');
INSERT INTO `customer` VALUES (21,'Jane Doe','F','631-911-1111','','','222 1st Ave, NY, NY','1987-10-10','','T','T');
INSERT INTO `customer` VALUES (22,'Matt Messina','M','631-333-4444','','matt.messina@gmail.com','321 Sayville Blvd, Sayville, NY','1987-02-10','','T','T');
INSERT INTO `customer` VALUES (23,'Mike Messina','M','631-521-4114','','mike.messina@gmail.com','321 Sayville Blvd, Sayville, NY','1989-02-15','','T','T');
INSERT INTO `customer` VALUES (24,'Robbie Messina','M','631-567-4444','','bobo.messina@gmail.com','321 Sayville Blvd, Sayville, NY','1991-02-10','','T','T');
INSERT INTO `customer` VALUES (25,'Erin Messina','F','631-511-2233','','erin.messina@gmail.com','321 Sayville Blvd, Sayville, NY',NULL,'','T','T');
INSERT INTO `customer` VALUES (26,'John Messina','M','631-567-4444','','john.messina@gmail.com','321 Sayville Blvd, Sayville, NY',NULL,'','T','T');
INSERT INTO `customer` VALUES (33,'John McNicholas','M',NULL,NULL,'johnmac31793@aim.com','49 Raymond St',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (34,'R. Vinicombe',NULL,NULL,NULL,NULL,'51 Craig Rd, Islip Terrace',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (35,'Brendan Ward','M',NULL,NULL,'bwardns26@aol.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (36,'Nick Nigio','M',NULL,NULL,'nigroll6@gmail.com','123 Sherry St, East Islip',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (37,'Alex Baier','M',NULL,NULL,'aj6yankee@aol.com','7 Dock Rd, East Islip',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (38,'James Caporsco','M',NULL,NULL,'capbatmd@netscape.net','114 Michael Rd, Oakdale, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (39,'Jee Bisch',NULL,'',NULL,'jeebisch@gmail.com','PO Box 336 St. James, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (40,'Joel Perez','M','631-589-6415',NULL,'bboyjoeziz@yahoo.com','28 Keswick Dr, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (41,'Joe Macedo','M','631-867-5309',NULL,'joeseph.macedo@gmail.com','1836 Westlawn Drive',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (42,'Luis Aceund','M',NULL,NULL,NULL,'454 Main St Apt D, Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (43,'Keith Byrnes','M',NULL,NULL,'akburnz@optonline.net','39 Patchouge Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (44,'Kevin Togher','M',NULL,NULL,'ktogher@gmail.com','28 Tellar Dr., Islip Terrace, NY, 11752',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (45,'Mohammad Zahid','M',NULL,NULL,'m2futuremj@aim.com','229 Bryant St, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (46,'Michael Zicocecca','M',NULL,NULL,'miczic@verizon.net','41 Rosemary Drive, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (47,'Bryan Brown','M',NULL,NULL,'bbrown3230@yahoo.com','23 Argyle Dr, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (48,'Nick Mucchio','M',NULL,NULL,'zeikda@optonline.net','68 Arline Lane, East Islip NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (49,'Reena Foundas','F',NULL,NULL,'r.foundas@yahoo.com','27 Freeport St, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (50,'Chip Cipriano','M',NULL,NULL,'cips50@yahoo.com','253 Wilson Blvd, Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (51,'Frank Esposito','M',NULL,NULL,'fwespo1986@yahoo.com','14 Esplande Dr, E. Patchouge NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (52,'Michael McNulty','M',NULL,NULL,'eichiefs39@yahoo.com','228 Marilynn St, East Islip, NY, 11730',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (53,'Juan Bautista','M',NULL,NULL,'juandnungia@hotmail.com','3151 Union Blvd, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (55,'Lio Grillo','M','516-111-2222',NULL,'lion4life@gmail.com','30 Madison Ave, Rockville Center, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (56,'Chad Homel','M',NULL,NULL,'chadhora@earthlink.net','101 Percy Williams, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (57,'Sean Gregory','M',NULL,NULL,'dudebro@vzw.blackberry.net','47 Fern Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (58,'Steve Berte','M',NULL,NULL,'sbert7@yahoo.com','11 Jefferson Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (59,'Joyce Sullivan','F',NULL,NULL,'sully1018@optonline.net','280 Belmare Ave #132 Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (60,'Eric Bruno','M',NULL,NULL,'','129 Timber Point Rd, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (61,'Brandon Fatigate','M',NULL,NULL,'fatscb@gmail.com','27 Ort Court, Sayville, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (62,'Lori Castronova','F',NULL,NULL,'ladymijo@yahoo.com','220 E Madison St, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (63,'Ed Flahery','M',NULL,NULL,'etflaherty@verizon.net','32 Roe Crt, Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (64,'Jay Benedito','M',NULL,NULL,'JBendetto@hotmail.com','220 Norwood St',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (65,'Mike Ferrugieri','M',NULL,NULL,'ferro30@aol.com','228 McCall Ave, West Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (66,'Anthony Buffolino','M',NULL,NULL,'tonybuff1@aol.com','92 Stellenwerf Ave, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (67,'Tom Ednie','M',NULL,NULL,'tom.ednie@gmail.com','138 5th Ave, Holtsville, NY, 11742',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (68,'Steve Ianello','M',NULL,NULL,'SIanello@essalte.com','86 Marrilyo St, East Islip, NY, 11752',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (69,'Robert Aharam','M',NULL,NULL,'','20-54 Laurel Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (70,'Stephen McGarity','M',NULL,NULL,'mogat2@hotmail.com','6 Aymer Ct',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (71,'Kevin Ottie','M',NULL,NULL,'kkey242@gmail.com','156 Glensummer Rd, Holtsville, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (72,'George Schmmidt','M',NULL,NULL,NULL,'855 Bay 8th St, West Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (73,'Chris Ciotrosz','M','631-111-2222',NULL,'cciotkosz@gmail.com','819 Main St, Holbrook, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (74,'Eric Herbst','M','516-777-1122',NULL,'eherbst@fardm.edu','106 Argyle Dr, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (75,'Jon Gersity','M','631-777-9999',NULL,'jonman1985@yahoo.com','16 Summerfield Circle, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (76,'Mike Stillwell','M',NULL,NULL,'mstillwell@gmail.com','363 Woodhollow Rd, Great River, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (77,'Brian Giglio','M','631-444-2222',NULL,'bgiglio@gmail.com','79 Babylon St, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (78,'Nancy Cirillo','F','631-444-6666',NULL,'ncirillo@aol.com','116 Marilynn St',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (79,'Brian Verdino','M',NULL,NULL,'Brian.Verdino@yahoo.com','127 Church Road, Great River, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (80,'Larry Shelortre','M',NULL,NULL,'axeifd17@aol.com','30 Sherwood Dr, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (81,'Chris Shea','M','631-555-1111',NULL,'killerlat459@aim.com','222 Wensley Lane, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (82,'Joe Ragusa','M','631-798-1244',NULL,'kragu2@yahoo.com','19 Salem Street, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (83,'Ryan Ragusa','M','516-777-9110',NULL,'kragu2@yahoo.com','19 Salem Street, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (84,'Don Schoeneman','M','516-777-9900',NULL,'schoeneman@wfcaero.com','48 Herbert Street, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (85,'Jim O\'Neill','M','631-111-3333',NULL,'joneil@yahoo.com','3 Fairwood Drive, Islip Terrace, NY',NULL,'Special longer notes for Jim O\'Neil',NULL,NULL);
INSERT INTO `customer` VALUES (86,'John Kozak','M','631-123-4455',NULL,'kozak@optonline.net','122 Hobart Street, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (87,'Joseph Oguliene','M','631-789-1234',NULL,'steffyjo@aol.com','136 Bayview Ave, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (88,'Maria Bonacore','Female','5167779900','','','',NULL,'','T','F');
INSERT INTO `customer` VALUES (90,'Martha Stewart','Female','5167779900','','stewartm@gmail.com','',NULL,'&lt;script&gt;alert(&quot;Hello!&quot;);&lt;/script&gt;','F','T');
INSERT INTO `customer` VALUES (91,'Eric Murphy','Male','6315894411','','emurph@gmail.com','',NULL,'&lt;script&gt;Badscript&lt;/script&gt;','F','F');
INSERT INTO `customer` VALUES (93,'Johnny Drama','Male','6315671111','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (94,'Tony Soprano','Male','6314567799','','soprano1@gmail.com','',NULL,'','F','T');
INSERT INTO `customer` VALUES (95,'donald trump','Male','7182223333','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (96,'ryan peterson','','6315897700','','ryanpeterson93@yahoo.com','23 Pine Street, Brentwood, NY 11717',NULL,'','F','F');
INSERT INTO `customer` VALUES (97,'Kenny Bonilla','Male','','','kennybonilla123@gmail.com','10 Blackmore Lane, East Islip, NY, 11730',NULL,'&lt;script&gt;SampleScript&lt;/script&gt;','F','F');
INSERT INTO `customer` VALUES (98,'Robert Doyle','','','','amish1@optonline.net','71 Stellerwarf Dr, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (99,'Pat McCabe','','6313333','','patchrismc@aol.com','50 Vail St, Islip, NY 11751',NULL,'','T','T');
INSERT INTO `customer` VALUES (100,'Mike Deloito','Male','','','sportsxtreme@aol.com','36 County View Lane, East Islip, NY ',NULL,'','F','F');
INSERT INTO `customer` VALUES (101,'Jason Cruz','','6314453','','jasoncruz@optonline.net','',NULL,'','F','T');
INSERT INTO `customer` VALUES (102,'Tom Lucie','Male','','','tmlucie@gmail.com','5 Moss Pl West Islip, NY 11795',NULL,'','F','F');
INSERT INTO `customer` VALUES (103,'Dan Gangi','','','','dan.gangi@gmail.com','14 S Harrison Ave, East Islip, NY 11795',NULL,'','F','F');
INSERT INTO `customer` VALUES (104,'Jon Rockfeld','Male','6314445555','','screwman3@aol.com','35 Woodcliff Rd, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (105,'Paul Guzzo','Male','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (106,'Wesley Bradley','','','','wessb24@gmail.com','550A West Montauk Highway',NULL,'','F','F');
INSERT INTO `customer` VALUES (107,'Jason Gumina','','','','jg9053@hotmail.com','360 Seacliff St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (108,'Vinny Saturnino','','','','defiant2091@yahoo.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (109,'Joel Moskowitz','','','','joeljean@optonline.net','66 Rocket Drive, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (110,'Richie Lundin','','','','alundin618@optonline.net','14 Menasha Lane, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (111,'Andrew Bawer','','','','bauer101631@gmail.com','32 Woodcliff Road, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (112,'Marc Giangreeorio','','','','mgiang5785@gmail.com','45 Perry Williams Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (113,'Melvin Scott','','','','melscott11@gmail.com','3 Arbell Dr, Brentwood, NY 11717',NULL,'','F','F');
INSERT INTO `customer` VALUES (114,'Kevin Conzone','Male','','','raizinfish@optonline.net','28 Abrew St, Bayshore, NY 11706',NULL,'','F','F');
INSERT INTO `customer` VALUES (115,'Joseph Grillo','','','','j.grillo55nyg@yahoo.com','1436 Gordine Dr, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (116,'Joe Gallo','','6314445566','','gallojoe@gmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (117,'Dakota Yonick','','','','dakotayonick53@hotmail.com','48 Wantagh Ave, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (118,'Ryan Becker','','','','maxsoundsdj@gmail.com','63 W Oakdale St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (119,'Ricky Silva','','','','rsilva1@att.blackberry.net','65 W Oakdale St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (120,'Mike Perri','','','','mperri@yahoo.com','41 Greenwood Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (121,'JR Reed','','','','socalbig6@gmail.com','95 Meadowfom Road',NULL,'','F','F');
INSERT INTO `customer` VALUES (122,'Jason Merrell','','631-444-9900','','bigjay_2@gmail.com','134 Rollstone Ave, West Sayville, NY 11796',NULL,'','F','F');
INSERT INTO `customer` VALUES (123,'James Roche','Male','','','rochej2609@gmail.com','459 China Road, Sayville, NY 11782',NULL,'','F','F');
INSERT INTO `customer` VALUES (126,'Mike Indolf','','','','mikein29@gmail.com','38 Indian Trace, Kings Park, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (127,'Keith Hilton','Male','','','','15 Pearl Ct, Sayville, NY 11782',NULL,'','F','F');
INSERT INTO `customer` VALUES (128,'Kevin Harrison','','','','dirtyharry7526@gmail.com','91 Richard Ave, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (129,'Theresa Zemah','','','','thegang1@optonline.com','60 Manhattan Blvd, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (130,'Rick Soldinger','','','','','1224 Saxon Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (131,'Danny Walsh','','','','CERT4USA@aol.com','19 Campbell Lane, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (132,'Bob Tierney','','','','btbb61@aol.com','PO Box 477 Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (133,'Ilene Mauner','','631 455-9009','','ileneevan@optonline.net','PO Box 184 Great River, NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (134,'Peter Weber','','','','banshee121w@aol.com','22 Robinhood Dr, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (135,'Tim Sassone','','6315680','631 433 5544','timsassone@hotmail.com','6 Summer Wind Ct, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (136,'Dave Schreyer','Male','','','schrd@farmingdale.edu','90 Richard Ave, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (137,'Josh Werner','','','','mistersofty201@aim.com','26 Andrew Ave, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (138,'Kyle Hubbany','','516-777-3311','(516) 666 8888','','23 Meroke Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (140,'Kyle Edsell','','631 589 1122','','edsellkyle@yahoo.com','151 Raymond St, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (141,'Logan Phillips','','','','logan.phillips631@gmail.com','55 Oakwood Hills Dr',NULL,'','F','F');
INSERT INTO `customer` VALUES (142,'Brian Johnson','','','','proshooter18@aol.com','18 Woods Place, Islip Terrace, NY 11757',NULL,'','F','F');
INSERT INTO `customer` VALUES (143,'George Costanza','','212-999-0099','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (145,'Hunter Edel','','5671100','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (146,'Kirk Zachary','','6315561122','','larkman1709@yahoo.com','4 Millwood Ct, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (147,'Phil Debrino','','6314431122','','hexplex311@hotmail.com','8 Anson Lane, West Sayville',NULL,'','F','F');
INSERT INTO `customer` VALUES (148,'Louis San Juan','','','','JenLou628@optonline.net','1209 Saxon Ave, Bayshore, NY 11706',NULL,'','F','F');
INSERT INTO `customer` VALUES (149,'Carolyn Johnson','','','','mmsssmteacher@yahoo.com','41 Irish Lane, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (150,'Mike Leverton','','','','levertonm@gmail.com','138 Merore Lane, East Islip NY 11736',NULL,'','F','F');
INSERT INTO `customer` VALUES (151,'Eric Crimi','','','','crimdawg922@msn.com','5 Robin Hood Dr., East Islip',NULL,'','F','F');
INSERT INTO `customer` VALUES (152,'Hunter Pszybyaski','','','','crabbyoldman@optonline.net','22 Vonhagen Ave, St, James, NY 11780',NULL,'','F','F');
INSERT INTO `customer` VALUES (153,'Gregg Neiola','','','','greggneiola@yahoo.com','19 Union Dr, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (154,'Anthony Ceraso','','','','venom96@optonline.net','111 Lincoln St, Farmingdale, NY 11735',NULL,'','F','F');
INSERT INTO `customer` VALUES (155,'Kevin Heams','','','','','11 Anesbury Ct, Islip Terrace',NULL,'','F','F');
INSERT INTO `customer` VALUES (156,'Kevin Bouza','','','','','36 Matinecock Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (157,'Frank Noviello','','','','','11 Wyandotta Lane, East Islip',NULL,'','F','F');
INSERT INTO `customer` VALUES (158,'Mitch Oldshein','','','','mrold3@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (159,'Joe Cozzolno','','','','','110 N Aleghanney, Lindenhurst, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (160,'Brian Salanchak','','','','alias1727@yahoo.com','272 Albany Ave, Lindenhurst, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (161,'Tony Schaller','','','','','1734 Spur Dr South, Islip NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (162,'Jason Hark','','','','jsnhark@gmail.com','119 Claywood Dr, Brentwood, NY 11717',NULL,'','F','F');
INSERT INTO `customer` VALUES (163,'Steve Hemberger','','','','stephen.hemberger@gmail.com','150 Lowell Ave, Islip Terrace',NULL,'','F','F');
INSERT INTO `customer` VALUES (164,'Peter Peluso','','','','redmenfootball68@aol.com','46 Wildwood CT, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (165,'Charlie Mauner','','','','pmwillp@msn.com','PO Box 184 Great River, NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (166,'Alexander Fisher','','','','aldog624@yahoo.com','1626 Roosevelt Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (167,'Ralph Rodriguez','','','','double_r_ralph@yahoo.com','440 Pine Dr, Brightwaters, NY 11718',NULL,'','F','F');
INSERT INTO `customer` VALUES (168,'Craig Volpe','','','','electman4u@aol.com','17 Melanni Place, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (169,'Tom Volpe','','','','lilboarder10@aol.com','26 Melanni Place, East Islip NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (170,'Gary Davidman','','','','gary.davidman@gsaig.gov','342 Garden City St, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (171,'Milton Lopera','','','','mlopera@optonline.net','91 Claridge Lane, East Islip',NULL,'','F','F');
INSERT INTO `customer` VALUES (172,'Nelson Marrero','','','','prnelly827@yahoo.com','26 Fairview Ave, Islip Terrace',NULL,'','F','F');
INSERT INTO `customer` VALUES (173,'Louis LaFemina','','','','deb308@optonline.net','207 Audwin Dr, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (174,'Stephen Smyth','','','','','40-A Greenwood Ave, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (175,'Neil Falcone','','','','falconene@aol.com','10 Overlook Drive, East Islip NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (176,'Mike Russo','','','','','107 E Madison St, East Islip NY ',NULL,'','F','F');
INSERT INTO `customer` VALUES (177,'Andrew Grosse','','','','grossefamily@mac.com','71 Shinnecock Ln, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (178,'Jake Goldsmith','','','','spongebobfan068@aim.com','19 Dana Lane, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (179,'Anthony Diesu','','','','patricia.diesu@gmail.com','150 Meadow Farm Road',NULL,'','F','F');
INSERT INTO `customer` VALUES (180,'Anthony Fragala','','','','sonshine5@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (181,'Adam Petry','','','','adam583@optonline.net','1267 Sycamore Ave, Bohemia, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (182,'Chris Parker','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (183,'Brett Slack','','','','bestgameseller@yahoo.com','24 Dock Road',NULL,'','F','F');
INSERT INTO `customer` VALUES (184,'Robert Slack','','','','','24 Dock Road',NULL,'','F','F');
INSERT INTO `customer` VALUES (185,'Dillon Jones','','631-667-1100','','dylan.jones@gmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (187,'Rob Parisi','','','','deniro18@aol.com','29 Tracy Ln, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (188,'Tyler Buffolino','','','','buff3mom@aim.com','92 Stellenwerf Ave, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (190,'John Smith','','631 444 9999','','jsmith@hotmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (192,'Joe Lirosi','','','','lirosij@yahoo.com','76 Roderick Rd, West Islip, NY 11785',NULL,'','F','F');
INSERT INTO `customer` VALUES (193,'Tom Kaminski','','6315891177','','tkaminski@optonline.net','16 Sutton Pl, Islip, NY',NULL,'','T','F');
INSERT INTO `customer` VALUES (194,'Scott Kohler','','','','scottdkohler@gmail.com','109 Harrisburg St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (195,'Dan King','','631-444-5566','','dtkjm@optonline.net','',NULL,'','F','T');
INSERT INTO `customer` VALUES (196,'Gigi Gibbons','','','','','165 Church Rd, Great River, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (197,'Lou Santonino','','','','santoman34@hotmail.com','32 Conlu Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (198,'Eli Acevedo','','','','eacevedos3@aol.com','9 Weldon St, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (199,'Jason Goldsmith','','','','jhgoldsm@asu.edu','19 Dana Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (200,'Cameron Vollmutt','','','','cvollmut@und.edu','89 River Road, Great River, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (201,'Dave Doxsee','','','','dave_doxsee@yahoo.com','17 Peony Lane, Commack, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (202,'Kenneth Kelliber','','','','kathykelliber@mhsinc.com','9 Percy Williams Dr, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (203,'Marty Bowden','','','','martyb419@verizon.net','123 Hobart St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (204,'Danielle Walsh','','','','dmariewalsh@yahoo.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (205,'Daniel Rizzo','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (206,'Jason Redding','','','','','19 Rocket Dr. East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (207,'Charles Reilly','','','','chas.rf@gmail.com','18 Wildwood Ct, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (208,'CJ Laidlaw','','','','chuck88@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (209,'Chris Leis','','','','mostdope93@aol.com','175 Connetquot Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (210,'Charlie Curran','','','','','171 Country Village Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (211,'Scott Godfrey','','','','scottgod@buffalo.edu','1024 Broadway, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (212,'Roger Bachler','','','','rogerb2713@yahoo.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (213,'John Daino','','','','erakoinz@optonline.net','4 West Bittermint St, Islip NY 11757',NULL,'','F','F');
INSERT INTO `customer` VALUES (214,'Jeaneen Ferrin','','','','eipride@optonline.net','205 Sherry St, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (215,'Tom O\'Neil','','','','tomoneil@yahoo.com','60 Hollins Lane, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (216,'Stephen Bauer','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (217,'John Bitler','','','','','48 Wensley Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (218,'Nicole Stassi','','','','nstassi@optonline.net','8 Division Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (219,'Lou Nicosia','','','','lounicosia1@gmail.com','2 Beverly Rd, Farmingdale, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (220,'Will Slevin','','','','wslevin11@gmail.com','1 Laurie Place, West Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (221,'Robert Hecht','','','','','128 Pear St, Brentwood, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (222,'Thomas O\'Neil','','','','','3 Fairwind Ct, Oakdale, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (223,'Frank DeOrio','','','','dknarf4@msn.com','16 Cynthia Ln, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (224,'Tommy Martone','','','','tmartone4@gmail.com','242 Islip Blvd, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (225,'Tom Mchugh','','','','uraqt@verizon.net','5 Timber Point Dr., East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (226,'Nicole Kelty','','','','toothangel32@gmail.com','280-23 Belmore Ave, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (227,'Shawn Tarquinio','','','','smt103@optonline.net','48 Pequot Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (228,'Jake Christy','','','','','17 Yuma Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (230,'Bob Faivre','','','','serfers@optonline.net','220 Marilynn St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (231,'Dan Huss','','','','ayanksfan@yahoo.com','11 2nd Ave, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (232,'Bill Powell','','','','mikki1216@optonline.net','32 Lagoon Pl, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (233,'Tom Zeman','','','','zmonster53@aol.com','11 Suffolk Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (234,'Phil Rosen','','','','prosen@optonline.net','2687 Arleigh Rd, East Meadow NY 11554',NULL,'','F','F');
INSERT INTO `customer` VALUES (235,'Chris Murino','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (236,'Keith Muller','','','','boostinf150@aol.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (237,'Mike Marriano','','','','mmorri8@pride.hofstra.edu','2728 Beatrice Lane, North Bellmore, NY 11710',NULL,'','F','F');
INSERT INTO `customer` VALUES (238,'Vincent DellAccio','','','','vincentd@century21aa.com','141 Eaton Lane, West Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (239,'David Arzuaga','','','','dave.arzuaga@gmail.com','280 Bellmore Ave Appt 114, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (240,'Rob Moore','','','','taram724@aol.com','221 Wensley Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (241,'Christopher Loos','','','','','387 Snedecor Ave, West Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (242,'Daniel Perez','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (243,'Mac McFaulds','','','','mac6688@aol.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (244,'J Tedone','','','','','229 Woodmere St, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (245,'James DiGiovanna','','','','jamesdigiovanna@aol.com','367 Woodhollow Road, Great River NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (246,'John Bergin','','','','aka8028@aol.com','431 Elmwood St, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (247,'Chris Havo','','','','','107 Merrell Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (248,'Bobby Reith','','','','rreith985@gmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (249,'Michael Chidichimo','','','','chidz@aol.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (250,'Frank Diakovasilis','','','','frankdiako@yahoo.com','118 Arbour St, West Islip NY 11795',NULL,'','F','F');
INSERT INTO `customer` VALUES (251,'Enrico Mule','','','','','19 Birch Rd, East Islip NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (252,'Marc Laskowski','','','','laus23@aol.com','85 Roslyn St, Islip Terrace NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (253,'Steven Snider','','','','ssnider.ice@gmail.com','13 Pinetree Lane, Great River, NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (254,'Ray Macggin','','','','raymacentertainment@gmail.com','13 Third Ave, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (255,'Joe Quinci','','','','dquinci@yahoo.com','PO Box 985 Great River, NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (256,'Rich Lundin','','','','','14 Merssha Lane, East Islip',NULL,'','F','F');
INSERT INTO `customer` VALUES (257,'Ray Vazquez',NULL,NULL,NULL,'rayray12TNL@aol.com','1321 Herzel Blvd. West Babylon NY','1989-10-12',NULL,NULL,NULL);
INSERT INTO `customer` VALUES (258,'Asif Ashia',NULL,NULL,NULL,NULL,'54 Beecher Ave, East Islip, NY','1988-12-05',NULL,NULL,NULL);
INSERT INTO `customer` VALUES (259,'Paul Mertens','','','','dmerts1@optonline.net','4 Naugatuck Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (260,'Billy Sakitis',NULL,NULL,NULL,'wsakitis@gmail.com','95 Wyandolte Ln, East Islip, NY','1980-04-21',NULL,NULL,NULL);
INSERT INTO `customer` VALUES (261,'Dan Winiarski','','','','levit161@aol.com','37 Simmons Dr, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (262,'Trevor Smith','','','','citrevorsmith@hotmail.com','34 Gwendolto Place, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (263,'Adam Menken','','','','adammenken56@gmail.com','18 Oakwood Hills Drive, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (264,'Joseph Doherty','','','','reflectionrecon@hotmail.com','255 E Main St Apt. 39, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (265,'James Missig','','','','entida1@yahoo.com','322 Woodhollow Road, Great River, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (266,'Michael Panaro','','','','','6 Nassau St, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (267,'Christian Maldonado','','','','cmaldon7@yahoo.com','125 Woodland St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (268,'Brian Barrett','','','','bbarrett27@vzw.blackberry.net','206 Cedarwood St, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (269,'Steve Cooper','','','','sjcooper96@aol.com','132 Woodland St, East Islip, NY 1130',NULL,'','F','F');
INSERT INTO `customer` VALUES (270,'Anthony Ferrandino',NULL,NULL,NULL,'ferrandino127@yahoo.com','6 Robin Hood Drive, East Islip, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (271,'Ross Harrison',NULL,NULL,NULL,'ross.harrison904@gmail.com','30 Kungunda Place, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (272,'Scott Stember','','','','sstember66@gmail.com','14 Fawn Lane, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (273,'Brendan Teague','','','','bai8K@yahoo.com','46 Lucille Drive, Sayville NY','1994-06-02','','F','F');
INSERT INTO `customer` VALUES (274,'Mike Conigliaro','','','','tmagic44@aol.com','','2015-03-11','','F','F');
INSERT INTO `customer` VALUES (275,'TJ Winter','','','','68winter@optonline.net','','2015-05-01','','F','F');
INSERT INTO `customer` VALUES (276,'Don Kinnear',NULL,NULL,NULL,'gymrat34@verizon.net','300 Rockaway Street, Islip Terrace, NY',NULL,NULL,NULL,NULL);
INSERT INTO `customer` VALUES (277,'Brendan Brown','','','','brownb34@gmail.com','94 Whitman Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (278,'Rich Sapianza','','','','simplc@aol.com','27 Tite Keel, East Islip NY','2015-01-14','','F','F');
INSERT INTO `customer` VALUES (279,'Tom Burke','','','','tommychugs@gmail.com','35 Fairview Ave, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (280,'Kevin Burke','','','','ma818ck@yahoo.com','29 Dunn Court, Sayville, NY 11782',NULL,'','F','F');
INSERT INTO `customer` VALUES (281,'Kenny Rojas','','','','specialk889@gmail.com','','1984-01-31','','F','F');
INSERT INTO `customer` VALUES (282,'Brian Senft','','','','brians160@yahoo.com','28 Keswick Drive, East Islip NY','2015-09-08','','F','F');
INSERT INTO `customer` VALUES (283,'Ryan Godfrey','','','','','1029 Broadway, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (284,'Jaime Moore','','','','moore.jcm@gmail.com','49 41st Street, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (285,'Eric Lubin','','','','emlubin1024@aol.com','412 Elmwood St, Islip Terrace, NY','1991-09-21','','F','F');
INSERT INTO `customer` VALUES (286,'John Cipolla','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (287,'Marc Mullan','','','','marczha@optonline.net','205 E. Nassau St, Islip Terrace, NY 11752','2015-06-16','','F','F');
INSERT INTO `customer` VALUES (288,'Kenny Trzaskalski','','','','ktibew25@yahoo.com','8 Crestwood Dr. Shirley, NY 11967',NULL,'','F','F');
INSERT INTO `customer` VALUES (289,'Bob Rowan','','','','','7 Garden Way, East Islip NY 11730','2015-12-31','','F','F');
INSERT INTO `customer` VALUES (290,'Matthew Dobkowski','','','','','134 Simmons Drive, East Islip NY 11730','1989-07-20','','F','F');
INSERT INTO `customer` VALUES (296,'Dion Sturtz','','','','dion2399@optonline.net','150 E Adams St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (298,'PJ Luobell','','','','pluobell@gmail.com','90 River Rd, Great River, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (300,'Brad Hill','','','','bthill87@gmail.com','29 Leeside Dr, Great River, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (302,'Bill Vogelsang','Male','','','wmvogelsang@gmail.com','153 Sherry St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (304,'Michael Lauro','','','','michaelvincenzo22@yahoo.com','589 Connetquot Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (307,'Ryan McGuickian','','','','mcgckr@aol.com','174 Irish Lane, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (309,'Gina VanDenburg','','','','gnboys70@optonline.net','194 Country Village Ln, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (311,'Kevin Morris','','','','stimmor62@gmail.com','62 E Madison St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (312,'Tom Kenney','','516-666-1122','','sirofsirs@yahoo.com','298 Roe Ave, Patchouge, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (314,'Jeff Kestetsky','','','','','25 Robin Hood Drive, East Islip NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (316,'Tom McCarthy','','','','ktsunshine57@aol.com','1213 Boston Ave, Bayshore, NY 11706',NULL,'','F','F');
INSERT INTO `customer` VALUES (317,'Brian Boucher','','','','','384 Great River Rd, Great River, NY 11739',NULL,'','F','F');
INSERT INTO `customer` VALUES (318,'Tina Jankowski','','','','','13 Deer Run, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (319,'Phil Bauccio','','','','ltcphil47@aol.com','20 Alan St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (320,'Will Powers','','','','powers.will@gmail.com','940 N. Broadway, Massapequa, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (321,'Anthony Argenti','','','','amai@optonline.net','273 Keswick Dr, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (322,'Angelo Lieuta','','','','','14 Thompson Dr, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (323,'Lenny Padula','','','','padulal6191@potsdam.edu','22 Simmons Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (324,'Stephen Benmingham','','','','bbermo4@verizon.net','28 1st Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (325,'Artie Sanchez','','','','','106 Wantagh Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (327,'Michael Rechner','','','','','58 Fitchburg St, Bayshore, NY 11706',NULL,'','F','F');
INSERT INTO `customer` VALUES (328,'Anthony Perry','','','','aperry06@hotmail.com','286 Overlook Dr. East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (329,'William Powell','','','','mikki1216@optonline.net','32 Lagoon Place, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (330,'Frank Darienzo','','','','','154 Front Ave, Brentwood, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (331,'Christine Belrose','','','','christine.belrose@gmail.com','145 Simmons Dr. East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (332,'Adam Triculis','','','','triculis28@yahoo.com','21 Wendover Rd, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (333,'Dave Fava','','','','dave@reddawnproductions.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (334,'Alex Sheridan','','','','jaio18@optonline.net','9 Patchouge Ave, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (335,'Dennis McGrath','','','','denmcgr@aol.com','108 Church Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (336,'Diane Thomas','','','','','26 Richard Ave, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (337,'Ryan James','','','','','10 Richmond St, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (338,'Vinny Velez','','','','subzero00101@gmail.com','8 S Harrison Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (339,'David Cunningham','','','','','32 Richard Ave, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (340,'Bryan Farrish','','','','bryanfarrish86@gmail.com','10 Quintuck Lane, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (341,'Justin Stiegert','','','','jstiegert@gmail.com','150 Gibbs Pond Rd, Nesconset, NY 11767',NULL,'','F','F');
INSERT INTO `customer` VALUES (343,'Scott Maltese','','','','smaltese83@optonline.net','187 Country Village Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (344,'Rich Rindos','','','','','26 Windsor St, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (345,'Eddie Martorella','','','','martorella1@verizon.net','11 Kemp St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (347,'Dan Stack','','','','danielstack81@gmail.com','1931 Finch Lane, Central Islip, NY 11722',NULL,'','F','F');
INSERT INTO `customer` VALUES (348,'Ryan Baist','','','','rbaist621@gmail.com','18 Argyle Dr, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (349,'Greg Iorio','','','','giorio@verizon.net','1046 Udall Rd, West Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (350,'Alex Thall','','','','baboon121@gmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (351,'Rob Esposito','','','','autowi@optonline.net','6 Westminster Lane, West Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (352,'Kyle Wade','','','','IWrestler140@aol.com','128 Commack Road, Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (353,'Reese McGuire','','','','RPM1300@optonline.net','6 Matinecock Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (354,'Damien McWilliams','','','','mcdamo81@yahoo.com','55 Fairview Ave, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (355,'Jim McGarity','','','','waterside@optonline.net','6 Atmar Court, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (356,'Ryan Glennon','','','','shaglennon@yahoo.com','3 Brian Drive, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (357,'Anthony Barbieri','','','','antjbarbieri@yahoo.com','20 Columbus Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (358,'Anthony Yetkofsky','','','','trashdaddy27@yahoo.com','16 Donna Pl, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (359,'Lonn Patton','','','','lonnpatton@yahoo.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (360,'Amy Carroll','','','','alcarroll@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (361,'Mike Gannon','','','','mgannon03@yahoo.com','231 Medea Way, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (362,'Tom Renzulli','','','','','22 Tyler Ave, West Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (363,'Bobby Dell Isola','','','','delasolman@gmail.com','20 Arline Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (364,'Anthony Manna','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (366,'Brian O\'Hara','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (367,'Ken Sepe','','','','kjsep63@verizon.net','63 Woodland Dr., East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (368,'John Fargnoli','','6315895577','','fargnoli.john@gmail.com','106 Providence Dr., Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (369,'Eric Ohman','','','','emanohman@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (370,'Anthony Leis Jr','','','','leis.anthony@yahoo.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (371,'John Crowley','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (372,'Gerard Faraone','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (373,'Justin Pyatt','','','','pyaguy6133@yahoo.com','16 Richmond St, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (374,'Ed Pepp','','','','ed2311@optonline.net','23 Tracy Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (375,'Joey Kornahrens','','','','jakorn@optonline.net','88 Ithaca St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (376,'Frank Zollner','','','','landsendstone@optonline.net','14 Nassau St, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (377,'Matthew Davis','','','','catm.davis@gmail.com','136 Union Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (378,'Ryan Carroll','','','','rcarroll2009pm@gmail.com','23 Brian Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (379,'Nicole Landrio','','631-433-5599','','fnf117@aol.com','117 Menoke Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (380,'Barry Witmer','','','','barry200419@yahoo.com','56 Marilyn St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (381,'Mike Capitelli','','','','smokintires91@aol.com','150 Mooney Pond Road, Selden, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (382,'Andrew Selweizer','','','','andywizer@optonline.net','22 Niagara St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (383,'Angelo Cecere','','','','ang213c@aol.com','569 Old Montauk Hwy, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (384,'Paul McEvoy','','','','pmcevoy@sjcny.edu','396 Hillside Ave, West Sayville, NY 11796',NULL,'','F','F');
INSERT INTO `customer` VALUES (385,'Matt Karl','','','','mattkarl34@aol.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (386,'Sean Carey','','','','','15 Hickory St, Central Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (387,'Jack McLean','','','','heckeyhead79@yahoo.com','16 Quintuck Ln, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (388,'Frank Buquicchio','','','','bqesq@optonline.net','',NULL,'','F','F');
INSERT INTO `customer` VALUES (389,'Harry Krause','','','','','57 Willow Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (390,'Richard Cuba','','','','','155 Islip Blvd, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (391,'Alex Wyman','','','','','27 Bogata Rd, Mastic Beach, NY 11951',NULL,'','F','F');
INSERT INTO `customer` VALUES (392,'Thomas Weir','','','','thomasweir@mac.com','10 Bay 2nd St, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (393,'Carlos Cabrera','','','','ccab101187@yahoo.com','16 Beecher Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (394,'Richard Diazzella','','','','mamapia6@aol.com','6 Mulberry Rd, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (395,'Charles Ferrera','','','','','70 Bayview Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (396,'Anthony DeFelice','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (397,'Robert Sawyer','','','','','21 Sutton Pl, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (398,'Steven Sarvis','','','','sarvis.steve@gmail.com','199 Grand Blvd, Deer Park, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (399,'Richard Huff','','','','richsteph06@yahoo.com','171 Keswick Drive, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (400,'Tara Turck','','','','taratturck@aol.com','112 Grant Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (401,'Mike Scarola','','','','hockeysbest14@optonline.net','74 Pequot Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (402,'Glenn Davis','','','','glenndavis93@yahoo.com','15 Viola Pl, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (403,'Steven Cerikos','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (404,'Elizabeth Allgeier','','','','elizabethall@optonline.net','42 Quintuck Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (405,'Steven Lemke','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (406,'Matt McNulty','','','','mcnutjob39@yahoo.com','228 Marilynn St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (407,'Mike Marriotl','','','','marricorp@hotmail.com','8 Juanita Ave, Huntington, NY 11743',NULL,'','F','F');
INSERT INTO `customer` VALUES (408,'Jake Abrami','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (409,'Charles Maneri','','','','jeepxj98@yahoo.com','129 Loop Drive, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (410,'Noah Charvat','','','','','9 Alexander Dr., East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (411,'Stephen Charvat','','','','','9 Alexander Dr., East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (412,'PJ Palladino','','','','pjkylee76@aol.com','171 Cedar Shore Dr., Massapequa, NY 11758',NULL,'','F','F');
INSERT INTO `customer` VALUES (413,'Alex Howell','','','','alexanderhowell@gmail.com','22 Fischer Ave, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (414,'Mike Connors','','','','mconnors@integratas.com','4 Tedel Court, West Babylon',NULL,'','F','F');
INSERT INTO `customer` VALUES (415,'Michael O\'Neil','','','','mjoneill@integratas.com','3 Fairwind Ct, Oakdale, NY 11769',NULL,'','F','F');
INSERT INTO `customer` VALUES (416,'Bill Hamilton','','','','','64 Hampton St, Sayville, NY 11782',NULL,'','F','F');
INSERT INTO `customer` VALUES (417,'Ed Fitzgerald','','','','','128 Marilynn St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (418,'Andrew Garbarino','','','','baker@gwu.edu','76 Collins Ave, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (419,'Mike Kerrigan','','','','marge.kerrigan@hotmail.com','20 Marilyn St, East Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (420,'Geoffrey Goldfader','','','','eastislipbball@yahoo.com','16 Deer Run, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (421,'Nick Riolo','','','','','27 Keswick Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (422,'Luke Feder','','','','luke_feder@yahoo.com','1731 Finch Lane, Central Islip NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (423,'Steven Marzocca','','','','stvmaz@yahoo.com','19 Erin Ct, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (424,'Nick Croce','','','','Croce53@aim.com','8 Karp Drive, Islip Terrace NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (425,'Marty Padino','','','','sickshotkid@aol.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (426,'Jonathan Hermann','','','','bucwinger@hotmail.com','1340 Spur Dr. S, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (427,'Russ Fina','','','','','30 Wyandanch Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (428,'Glenn Herbst','','','','hpal5@aol.com','106 Argyle Dr, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (429,'David Hinde','','631-999-0011','','hinde40@yahoo.com','41 Abrew St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (430,'Alex Messino','','','','eifreak@aol.com','20 Robinhood Dr. East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (431,'Drew Schirmer','','','','yank1220@optonline.net','45 Union Ave, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (432,'James Boehning','','','','jamesboehning@gmail.com','226 Marilynn St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (433,'Steve Hines','','','','Hinz4118@verizon.net','118 New York Ave, Smithtown, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (434,'Rob Abramski','','589-3344','','sample@yahoo.com','64 Hampton St, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (435,'Michael Murphy','','','','mmjm11@optonline.net','11 Tracy Ln, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (436,'Matt Ramada','','631-555-1122','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (437,'Matthew Meier','','567-9988','','eihockey42@yahoo.com','97 Jefferson St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (438,'Rob Cassidy','','','','rcassidy1212@yahoo.com','59 Ridgefield Dr, Shoreham, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (439,'Jack Zimmermann','','','','thezimmermanns@yahoo.com','14 William Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (440,'Charlie Zimmermann','','','','thezimmermanns@yahoo.com','14 William Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (441,'Erica Blas','','','','eriobla@aol.com','56 Casement Ave, Central Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (443,'Thomas McCarthy','','','','McSwede318@aol.com','301B Terry Rd, Smithtown, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (444,'Bobby Cordina','','','','rcordina2112@yahoo.com','16 Sherwood Dr., East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (445,'Brendan Watson','','','','bwatson2496@yahoo.com','167 Washington St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (446,'Rick Sambo','','','','magnumpri@verizon.net','228 Wensley Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (447,'Colton Banville','','','','cjban06@aol.com','38 Greenwood Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (448,'Ryan Cox','','','','sayvillebaseball@aol.com','218 Sayville Blvd., Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (449,'Lisa Moran','','','','lmoran59@aol.com','67 Harbor Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (450,'Joe Maurio','','631-774-8017','','','10 Dewey St, Sayville, NY 11782',NULL,'','F','F');
INSERT INTO `customer` VALUES (451,'Joe Arma','','','','e.wrestler66@aim.com','131 Simmons Drive, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (452,'Bill Kearney','','','','','8 Valenic Pl, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (453,'Jen Person','','631-786-0864','','','17 Pine St, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (454,'Steven Vogel','','','','','3521 Union Blvd. Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (455,'Wayne Belucci','','','','w.bellucci@hotmail.com','43 Sherwood Dr., East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (456,'Anthony Messina','','','','','30 West Gate Drive',NULL,'','F','F');
INSERT INTO `customer` VALUES (457,'Kristi Cruz','','','','kristicruz@optonline.net','92 Herbert St, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (458,'Al Navaro','','','','minimedic@optonline.net','331 Ferndale Blvd., Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (459,'Matt Kelly','','','','kellyme5@aol.com','46 Elliot St, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (460,'Nick Viviano','','','','nviviano66@yahoo.com','266 Marilynn St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (461,'Angelo Auricchio','','','','','',NULL,'','F','F');
INSERT INTO `customer` VALUES (462,'Aaron Thiesen','','','','','15 Shamokin Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (463,'Victor Giardina','','','','hammerrunuts@aol.com','27 Hollister Lane',NULL,'','F','F');
INSERT INTO `customer` VALUES (464,'Jack Carroll','','','','jtcarroll45@optimum.net','45 Quail Run, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (465,'Steve Shea','','','','eibballplaya@yahoo.com','91 Wantagh Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (466,'John Koopman','','','','','10 Sandpiper Lane',NULL,'','F','F');
INSERT INTO `customer` VALUES (467,'Darrell Schober','','','','','201 Rollstone Ave, W Sayville, NY 11796',NULL,'','F','F');
INSERT INTO `customer` VALUES (468,'John Dimitri','','','','jldimitri@optonline.net','116 Baltimore Ave, Oakdale, NY 11769',NULL,'','F','F');
INSERT INTO `customer` VALUES (469,'Rich Subject','','','','richard.c.subject@gmail.com','19 Jenkins St, Islip, NY 11751',NULL,'','F','F');
INSERT INTO `customer` VALUES (470,'Chris Daddio','','','','chris.daddio22@gmail.com','64 S. Ocean Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (471,'Steve Rowland','','','','webster0320@aol.com','89 West Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (472,'Kraig Batkiewicz','','','','kraig631@yahoo.com','49 Fitchburg St, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (473,'Rod Pearce','','','','pearcebusmaint@aol.com','1514 Denver Ave, Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (474,'Rich Calabrese','','','','EIredmen07@yahoo.com','85 Manhattan Blvd.',NULL,'','F','F');
INSERT INTO `customer` VALUES (475,'Mike Legutko','','','','mleg522@hotmail.com','18 Doulop Ct, Commack, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (476,'Steve Sonkin','','','','slzonk@aol.com','20A Greenwood Ave, East Islip, NY 11730',NULL,'','F','F');
INSERT INTO `customer` VALUES (477,'Joe Fischer','','','','jfish751170@yahoo.com','39 Greenwood Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (478,'Travis Pitre','','','','travisp32@gmail.com','162 Division Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (480,'Paul Bodnar','','','','matteach1983@optonline.net','317 Medea Way, Central Islip, NY 11722',NULL,'','F','F');
INSERT INTO `customer` VALUES (481,'Rich Griffin','','','','ffd072@hotmail.com','',NULL,'','F','F');
INSERT INTO `customer` VALUES (482,'Timothy Monahan','','','','timothydmonahan@gmail.com','220 Irish Lane, Islip Terrace, NY 11752',NULL,'','F','F');
INSERT INTO `customer` VALUES (483,'Carmen Guecia','','','','','147 Max A Circle, Central Islip, NY 11722',NULL,'','F','F');
INSERT INTO `customer` VALUES (484,'Rob Mauro','','','','robmauro@optonline.net','71 Campbell Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (485,'Nick Lacetera','','','','NCLacetera@pafcu.net','31 N Ocean Ave, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (486,'Thomas Coan','','','','','12 William Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (487,'Jon Mendes','','','','jmendes17@aol.com','15 Oakwood Hills Dr, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (488,'Raymond Fomby Jr','','','','icewater6645@aol.com','66 Quintuck Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (489,'Ken Craver','','','','KenCraver@gmail.com','290 Johnson Ave',NULL,'','F','F');
INSERT INTO `customer` VALUES (490,'Rick Sobotica','','','','rick@greatsouthbaybrewery.com','2309 Union Blvd., Bayshore, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (491,'Bill Barc','','','','tqbilly@yahoo.com','124 Lenox Rd, North Babylon, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (492,'Steve Behar','','','','','19 Hollister Lane, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (493,'Amy Heller','','','','amymccb@optonline.net','38 E. Walnut St, Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (494,'Dan Sabino','','','','dsabino311@aim.com','2611 Union Blvd',NULL,'','F','F');
INSERT INTO `customer` VALUES (495,'Dan Murphy','','','','','PO Box 424 Central Islip',NULL,'','F','F');
INSERT INTO `customer` VALUES (496,'Kevin Tice','','','','','1540 Agate St, Bayshore, NY 11706',NULL,'','F','F');
INSERT INTO `customer` VALUES (497,'Richard Thomesen','','','','chilllaxeng@gmail.com','51 Campbell Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (498,'Shawn Dunn','','','','','37 Irish Lane, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (499,'Eric Livoti','','','','emlivoti@aol.com','6 Karp Dr, Islip Terrace, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (500,'Adam Nash','','','','adamleenash@yahoo.com','53 Regina Drive, Sayville, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (501,'Peter Coppinger','','','','socpete@aol.com','22 Division Ave, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (502,'George Podlaha','','','','thepodhouse@yahoo.com','31 Woodland St, East Islip, NY',NULL,'','F','F');
INSERT INTO `customer` VALUES (505,'Michael Rich','','','','mtrich638@hotmail.com','42 Hemlock St, Islip, NY 11751',NULL,'','F','F');