$(document).ready(function(){

	/* When search button is clicked, move other fields down and
	show information based on search results. 
	1.) If search returns a match, display customer history and information
	2.) If partial match, return top results and ask user which to choose
	3.) If no matches, ask user if they want to add new customer */
	$('.cust-search-button').click(function() {
		var customerName = document.getElementById("customer_name").value;

		if(customerName.length > 0){
			$(".customer-history").show(300);
			document.getElementById("customer-history-label").innerHTML = customerName;
		}
		else {
			$("#no-customer-returned").show(300);
		}
	});

	/* This closes the window showing customer history and informaton */
	$('#cust-history-close').click(function(){
		$(".customer-history").hide(300);
	});

	/*
	If the user selects Yes (they do want to add a new customer), do you want users to still make the 
	appointment, or first add the customer by getting their info, then make the appointment ?
	*/
	$('#no-cust-btn-yes').click(function(){
		
	});

	/* If user does not want to add new customer, close no-customer-returned window */
	$('#no-cust-btn-no').click(function(){
		$("#no-customer-returned").hide(300);
	});

	//Sets up the datepicker
	$('.datepicker').datepicker({
		todayBtn:"linked",
		autoclose:true,
		todayHighlight:true,
		daysOfWeekDisabled:'0'
	});

	//Pre-fill Date with today's date
	var today = new Date();
	var day = today.getDate();
	var month = today.getMonth() + 1; //Jan = 0
	var year = today.getFullYear();
	$('.datepicker').datepicker('update', month+"/"+day+"/"+year);


	//Time Picker
	$('#appt-timepicker').timepicker();

	//Sets up Calendar
	$('.calendar').fullCalendar({
		defaultView:'agendaDay',
		contentHeight:715,
		slotDuration:'00:15:00',
		minTime:"09:00:00",
		maxTime:"19:30:00",
		allDayText: "",

		/*arranges buttons on top*/
		/*CSVs appear adjacent,
		items seperated by space appear with a gap */
		header: {
			left:'prev',
			center: 'title',
			right:'today next'
		},
		editable: true,
		selectable:true,
		selectHelper: true


		/*
		events: [
			{
				title: 'Haircut',
				start: '2014-12-29T09:00:00',
				end: '2014-12-29T09:30:00'
			}
		]
		*/

	});

	/* This method will display appointment on calendar when the "Make Appointment" button is
	clicked. */
	$('.make_appt_btn').click(function(event){
		//This will prevent the page from reloading when button is clicked
		event.preventDefault();

		//Get fields that user entered. These will be used to create event in database
		var customerName = document.getElementById("customer_name").value;
		var apptDateIn = document.getElementById("date").value; //MM/DD/YYYY
		var apptTime = document.getElementById("appt-timepicker").value; //HH:MM AM
		var apptTitle = document.getElementById("service-dropdown").value;

		//call formatDate method to change format of date
		var apptDate = formatDate(apptDateIn);

		//set color of event object based on apptTitle
		var apptColor = '#3A87AD';
		if(apptTitle === 'Haircut'){
			apptColor = '#3A87AD';
		}
		else if (apptTitle === 'Color'){
			apptColor = '#F58839';
		}
		else if (apptTitle === 'Unavailable'){
			apptColor = '#F45245';
		}
		
		//Create event object which will be added to calendar
		var eventData
		eventData = {
			title: apptTitle,
			start: apptDate+'T11:30:00',
			end: apptDate+'T12:30:00',
			color: apptColor
		};
		$('.calendar').fullCalendar('renderEvent', eventData, true);

		//Clear fields on form
		document.getElementById("customer_name").value = "";
		document.getElementById("notes_area").value = "";
	});

	//JQuery DOM manipulation to have the full-calendar show columns for each employee
	/*
	$(".fc-day-grid .fc-bg .fc-day").after("<td class=\"employee_col\">Jackie</td>");
	$(".fc-day-grid .fc-bg .fc-day").after("<td class=\"employee_col\">Melvin</td>");
	$(".fc-day-grid .fc-bg .fc-day").after("<td class=\"employee_col\">Doug</td>");
	$(".fc-day-grid .fc-bg .fc-day").after("<td class=\"employee_col\">Tiara</td>");
	$(".fc-day-grid .fc-bg .fc-day").after("<td class=\"employee_col\">Kieron</td>");

	$(".fc-time-grid .fc-bg .fc-day").after("<td class=\"fc-widget-content\"></td>");
	$(".fc-time-grid .fc-bg .fc-day").after("<td class=\"fc-widget-content\"></td>");
	$(".fc-time-grid .fc-bg .fc-day").after("<td class=\"fc-widget-content\"></td>");
	$(".fc-time-grid .fc-bg .fc-day").after("<td class=\"fc-widget-content\"></td>");
	$(".fc-time-grid .fc-bg .fc-day").after("<td class=\"fc-widget-content\"></td>");

	$(".fc-day-grid .fc-bg .fc-day").remove();
	$(".fc-time-grid .fc-bg .fc-day").remove();
	*/
});

/*
This function takes in a date that is generated by the DatePicker.
The date argument needs to be converted to the format accepted by the event object
for the calendar.
The argument is in the following form: MM/DD/YYYY
The returned date is in the following form: YYYY-MM-DD
*/
function formatDate(dateIn) {	
	var x = dateIn.indexOf('/');
	var y = dateIn.lastIndexOf('/');

	var month = dateIn.substring(0, x);
	var day = dateIn.substr((x + 1), 2);
	var year = dateIn.substr((y + 1));

	return year + "-" + month + "-" + day;
}