INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("John McNicholas", "M", "49 Raymond St", "johnmac31793@aim.com");
INSERT INTO CUSTOMER (Name, HomeAddress) VALUES ("R. Vinicombe", "51 Craig Rd, Islip Terrace");
INSERT INTO CUSTOMER (Name, Gender, EmailAddress) VALUES ("Brendan Ward", "M", "bwardns26@aol.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Nick Nigio", "M", "123 Sherry St, East Islip", "nigroll6@gmail.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Alex Baier", "M", "7 Dock Rd, East Islip", "aj6yankee@aol.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("James Caporsco", "M", "114 Michael Rd, Oakdale, NY", "capbatmd@netscape.net");
INSERT INTO CUSTOMER (Name, EmailAddress) VALUES ("Jee Bisch", "jimbisch@gmail.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Joel Perez", "M", "28 Keswick Dr, East Islip, NY", "bboyjoeziz@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Joe Macedo", "M", "1836 Westlawn Drive", "joeseph.macedo@gmail.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress) VALUES ("Luis Aceund", "M", "454 Main St Apt D, Islip, NY");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Keith Byrnes", "M", "39 Patchouge Ave, East Islip, NY", "akburnz@optonline.net");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Kevin Togher", "M", "28 Tellar Dr., Islip Terrace, NY, 11752", "ktogher@gmail.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Mohammad Zahid", "M", "229 Bryant St, Islip Terrace, NY", "m2futuremj@aim.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Michael Zicocecca", "M", "41 Rosemary Drive, East Islip, NY", "miczic@verizon.net");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Bryan Brown", "M", "23 Argyle Dr, East Islip, NY", "bbrown3230@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Nick Mucchio", "M", "68 Arline Lane, East Islip NY", "zeikda@optonline.net");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Reena Foundas", "F", "27 Freeport St, East Islip, NY", "r.foundas@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Chip Cipriano", "M", "253 Wilson Blvd, Islip, NY", "cips50@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Frank Esposito", "M", "14 Esplande Dr, E. Patchouge NY", "fwespo1986@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Michael McNulty", "M", "228 Marilynn St, East Islip, NY, 11730", "eichiefs39@yahoo.com");
INSERT INTO CUSTOMER (Name, Gender, HomeAddress, EmailAddress) VALUES ("Juan Bautista", "M", "3151 Union Blvd, East Islip, NY", "juandnungia@hotmail.com");